## @file
# TianoCore Code Review Archive Service Flask Application
#
# Copyright (c) 2021, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
##
'''
TianoCore Code Review Archive Service Flask Forms
'''
from email.policy import default
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, IntegerField, PasswordField

class WebhookConfigurationForm(FlaskForm):
    GithubRepo          = StringField(
        'GithubRepo',
        description='Github repository name of form orgname/reponame (e.g. tianocore/edk2).'
        )
    GithubToken         = PasswordField(
        'GithubToken',
        description='40 character hex string that is a Personal Access Token created in GitHub User->Settings->Developer Settings->Personal access tokens.'
        )
    GithubWebhookSecret = PasswordField(
        'GithubWebhookSecret',
        description='64 character hex string that is secret used to validate payloads received from GitHub.'
        )
    EmailArchiveAddress = StringField(
        'EmailArchiveAddress',
        description='The TO address for emails address generated by this webhook service.'
        )
    SendEmail           = SelectField(
        'SendEmail',
        description = 'True to enable sending emails.  False to disable sending emails.',
        choices=[('',"False"),('1',"True")],
        coerce=bool
        )
    LargePatchLines     = IntegerField(
        'LargePatchLines',
        description='Maximum number of patch lines before file filtering is enabled.  Default is 500 lines.',
        default=500
        )
    MaintainersTxtPath  = StringField(
        'MaintainersTxtPath',
        description='Path to Maintainers.txt in the repository.  Default is Maintainters.txt in the root of the repository.',
        default='Maintainers.txt'
        )
    save                = SubmitField('Save')
    cancel              = SubmitField('Cancel')
    home                = SubmitField('Home')
